<a href="https://colab.research.google.com/github/ginomempin/deep-learning-tutorials/blob/master/src/tutorials/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch 

In [0]:
import numpy as np
import torch

**Basic PyTorch Tensors**

In [17]:
 t1 = torch.tensor([1, 2, 3, 4, 5, 6])
 print(t1) 
 print(t1.dtype)
 print(t1[0], v[1], v[2])
 print(t1[1:4])
 print(t1[1:])

tensor([1, 2, 3, 4, 5, 6])
torch.int64
tensor(1) tensor(2) tensor(3)
tensor([2, 3, 4])
tensor([2, 3, 4, 5, 6])


In [18]:
 t2 = torch.FloatTensor([1, 2, 3, 4, 5, 6])
 print(t2) 
 print(t2.dtype)
 print(t2.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


**Rearranging Tensor Shape**

In [19]:
t1.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [20]:
t1.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

**Converting Between Numpy Arrays and PyTorch Tensors**

In [21]:
numpy_arr = np.array([1, 2, 3, 4, 5])
torch_tns = torch.from_numpy(a)
print(torch_tns)
print(torch_tns.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64


In [23]:
torch_tns = torch.Tensor([1, 2, 3, 4])
numpy_arr = torch_tns.numpy()
print(numpy_arr)
print(numpy_arr.dtype) 

[1. 2. 3. 4.]
float32
